name: Docker CI/CD Pipeline to EC2 with Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      # - name: Run tests
      #   run: npm test

      - name: Build Docker image
        run: docker build -t myapp:${{ github.sha }} .

      - name: Check Docker Hub Username
        run: echo "${{ secrets.DOCKERHUB_USERNAME }}"

      - name: Check Docker Hub Token
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker tag myapp:${{ github.sha }} dhanushkata102/myapp:v${{ github.sha }}
          docker push dhanushkata102/myapp:v${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ec2-35-170-73-239.compute-1.amazonaws.com
        username: ec2-user
        key: -----BEGIN RSA PRIVATE KEY-----
MIIEpQIBAAKCAQEAu0PpqaqTc+tsiJLV1FTm1RqUG+UhWIuFORGwcPsmhcytEayx
9uIAgllblvqJQ/QifH+sjn0BTZwXgHPpw/dn/0DZ9BEdN7pe/okyUSFEXkGA7IxV
4vtD1SEYFCm9Nl+akaZGsxkQe/8N4MWB3cjuBFjDfCg6rccRW1Td1pYvOND8114F
jGkNYTusX0BhqYx4ohwLbspxCe+CZ4vW0LQH9HC/b5jbAl/UCCFr+gsHufHcXM4S
7twse2y8i22w5ZiMqInwsddnngSefONA+Yhw3ELU9UDdILG0zWFLWp0wElAlMusN
6iDve7t1om5A79VzjqMfknWVbQo+/ZN7LYC0pQIDAQABAoIBAQCi7ceS8vIv3Rkl
Cnw4rVXY+7L5QjXtEBbtPFLDOgCeUSITSqncH25J+u0RQxHCqdqHb532qxRDLhfU
jwVIly1IjGgVTf6ZyfF0jHHW3JbbWyqMpNzlC7BM8uo8QMR7Vlrpdj30/U22VIcC
lVUUXgmYhpIup+HF6HlVeVU5qpmTV+RfPaSkrq7lLGf4v0sJQCxy8mhoqzFCKIek
UOzrOuRawLMRdJfpDPcNx13onWDOlFE2P2uWtPnVLErNbJEdz1EnhNnESgITX1ej
exahkyTmqknh3suPw7wQXtDXgZN7uXnzwCGRODC0oflAXSF7K7Nh19gKJdVu7eD1
fqAwn2LRAoGBAN00DJtoYLYO5UnVd3/LxBU8aXhc5Od8S6OhC9hG5irvQok07k85
NF3kfkavj817y1IAAh7mkrKrZuKBjaCWo6YvvDIV85YYGUlIFU+0HkmVDmK+vYUi
oC/fmj/T9a8BRhP4ChMB3HJZn2fZX5QtkNwhD2LRLkRcIkcl/VAAxThLAoGBANi5
KiPAIcEiaLcsBq3Ir1ipdeUuSn3yKhW0/N94HaMrDO0lWdDiF6cVAhOHq2dx3cXr
cGjzitMlo9Vu95P8/dkrdwRD6WSZEyIw7l3BkpEwndfADhXkrZkq7n6hWRDD+YB+
/IpokuxiFYbDFZk8ivW4xfWH+3GDif3A2lT8WpDPAoGBAMYcIppg3hTPvGznATJ0
hXXbeD5zPBNST9AJoTkfLm8Pf9Cwlipf+lWJGcsm2yzWjV8wYLXaHVJljiyYiQZl
Q8XIBM36uQEZLjRimaubjnCqTYsEd2owe7TElzpJFEWbZ27k++jQBuZm/AwfM6nb
MVzlQwlmfQB+X7jG/lrThc6HAoGBAItF0zLOUeLPvgOYo2IiyaxsmnsBWJW/fhQd
DzR8+G7XR6NOkX2PDiwtb/wk/52mqyJ5vu9zMw+l7LdIbIoJ1wgsyntPOTmQtZ8P
Wt+dehcb6xOvNF4Vawo3cLSn85i2mCxfbuNzeJe4IKVN0R98rMBkUbMMBCZapd8Q
hD6BPaI5AoGAREDaKWcmJmJJ7psZhPNYPMmXUbaNpWnlj0zFR/kP2zMbNIXl1xOO
tUvhKrePylEIQtQOwk/u1y+v2OXk/sjByrSAo2xpYywVw7DH31AbeSyO5c3JD94p
SkT7/DiGr50aAYFLcgA3bTXuuC/mKXy2ZRBjvxfJs9qFZOl2gmd1x+M=
-----END RSA PRIVATE KEY-----
        script: |
          docker stop myapp || true
          docker rm myapp || true
          docker pull dhanushkata102/myapp:${{ github.sha }}
          docker run -d -p 80:80 --name myapp dhanushkata102/myapp:${{ github.sha }}
        port: 22
