name: Docker CI/CD Pipeline to EC2 with Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      # - name: Run tests
      #   run: npm test

      - name: Build Docker image
        run: docker build -t myapp:${{ github.sha }} .

      - name: Check Docker Hub Username
        run: echo "${{ secrets.DOCKERHUB_USERNAME }}"

      - name: Check Docker Hub Token
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker tag myapp:${{ github.sha }} dhanushkata102/myapp:v${{ github.sha }}
          docker push dhanushkata102/myapp:v${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ec2-35-170-73-239.compute-1.amazonaws.com
        username: ec2-user
        key: -----BEGIN RSA PRIVATE KEY-----
            MIIEpQIBAAKCAQEAu0PpqaqTc+tsiJLV1FTm1RqUG+UhWIuFORGwcPsmhcytEayx9uIAgllblvqJQ/QifH+sjn0BTZwXgHPpw/dn/0DZ9BEdN7pe/okyUSFEXkGA7IxV4vtD1SEYFCm9Nl+akaZGsxkQe/8N4MWB3cjuBFjDfCg6rccRW1Td1pYvOND8114FjGkNYTusX0BhqYx4ohwLbspxCe+CZ4vW0LQH9HC/b5jbAl/UCCFr+gsHufHcXM4S7twse2y8i22w5ZiMqInwsddnngSefONA+Yhw3ELU9UDdILG0zWFLWp0wElAlMusN6iDve7t1om5A79VzjqMfknWVbQo+/ZN7LYC0pQIDAQABAoIBAQCi7ceS8vIv3RklCnw4rVXY+7L5QjXtEBbtPFLDOgCeUSITSqncH25J+u0RQxHCqdqHb532qxRDLhfUjwVIly1IjGgVTf6ZyfF0jHHW3JbbWyqMpNzlC7BM8uo8QMR7Vlrpdj30/U22VIcClVUUXgmYhpIup+HF6HlVeVU5qpmTV+RfPaSkrq7lLGf4v0sJQCxy8mhoqzFCKIekUOzrOuRawLMRdJfpDPcNx13onWDOlFE2P2uWtPnVLErNbJEdz1EnhNnESgITX1ejexahkyTmqknh3suPw7wQXtDXgZN7uXnzwCGRODC0oflAXSF7K7Nh19gKJdVu7eD1fqAwn2LRAoGBAN00DJtoYLYO5UnVd3/LxBU8aXhc5Od8S6OhC9hG5irvQok07k85NF3kfkavj817y1IAAh7mkrKrZuKBjaCWo6YvvDIV85YYGUlIFU+0HkmVDmK+vYUioC/fmj/T9a8BRhP4ChMB3HJZn2fZX5QtkNwhD2LRLkRcIkcl/VAAxThLAoGBANi5KiPAIcEiaLcsBq3Ir1ipdeUuSn3yKhW0/N94HaMrDO0lWdDiF6cVAhOHq2dx3cXrcGjzitMlo9Vu95P8/dkrdwRD6WSZEyIw7l3BkpEwndfADhXkrZkq7n6hWRDD+YB+/IpokuxiFYbDFZk8ivW4xfWH+3GDif3A2lT8WpDPAoGBAMYcIppg3hTPvGznATJ0hXXbeD5zPBNST9AJoTkfLm8Pf9Cwlipf+lWJGcsm2yzWjV8wYLXaHVJljiyYiQZlQ8XIBM36uQEZLjRimaubjnCqTYsEd2owe7TElzpJFEWbZ27k++jQBuZm/AwfM6nbMVzlQwlmfQB+X7jG/lrThc6HAoGBAItF0zLOUeLPvgOYo2IiyaxsmnsBWJW/fhQdDzR8+G7XR6NOkX2PDiwtb/wk/52mqyJ5vu9zMw+l7LdIbIoJ1wgsyntPOTmQtZ8PWt+dehcb6xOvNF4Vawo3cLSn85i2mCxfbuNzeJe4IKVN0R98rMBkUbMMBCZapd8QhD6BPaI5AoGAREDaKWcmJmJJ7psZhPNYPMmXUbaNpWnlj0zFR/kP2zMbNIXl1xOOtUvhKrePylEIQtQOwk/u1y+v2OXk/sjByrSAo2xpYywVw7DH31AbeSyO5c3JD94pSkT7/DiGr50aAYFLcgA3bTXuuC/mKXy2ZRBjvxfJs9qFZOl2gmd1x+M=
            -----END RSA PRIVATE KEY-----
        script: |
          docker stop myapp || true
          docker rm myapp || true
          docker pull dhanushkata102/myapp:${{ github.sha }}
          docker run -d -p 80:80 --name myapp dhanushkata102/myapp:${{ github.sha }}
        port: 22
